name: Descent 3 Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
      - '**/.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
      - '**/.github/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - runner: windows-latest
            preset: win
            cc: cl
            cxx: cl
          - runner: macos-12 # This is supposed to be Intel for now, and what macos-latest is defaulting to for some reason (as of 04/2024)
            preset: mac
            cc: cc
            cxx: c++
          - runner: macos-14 # This is supposed to be M1
            preset: mac
            cc: cc
            cxx: c++
          - runner: ubuntu-latest
            preset: linux
            cc: gcc
            cxx: g++
          - runner: ubuntu-latest
            preset: linux
            cc: clang
            cxx: clang++
          - runner: ubuntu-latest
            preset: linux-32
            cc: gcc
            cxx: g++

    runs-on: ${{ matrix.os.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Install macOS dependencies
        if: ${{ matrix.os.preset == 'mac' }}
        run: |
          # Install packages from Homebrew
          brew bundle install

      - name: Install Linux dependencies
        if: ${{ matrix.os.preset == 'linux' }}
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            ninja-build cmake g++ libsdl1.2-dev libsdl-image1.2-dev libncurses-dev zlib1g-dev

      - name: Install Linux dependencies for 32 bit build
        if: ${{ matrix.os.preset == 'linux-32' }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y --no-install-recommends \
            ninja-build cmake g++ g++-multilib libsdl1.2-dev:i386 libsdl-image1.2-dev:i386 libncurses-dev:i386 zlib1g-dev:i386

      - name: Configure CMake
        env:
          CC: ${{ matrix.os.cc }}
          CXX: ${{ matrix.os.cxx }}
          VCPKG_ROOT: C:/vcpkg
        run: cmake --preset ${{ matrix.os.preset }}

      - name: Debug Build
        run: cmake --build --preset ${{ matrix.os.preset }} --config Debug --verbose

      - name: Release Build
        run: cmake --build --preset ${{ matrix.os.preset }} --config Release --verbose

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_${{ matrix.os.runner }}_${{ matrix.os.cxx }}
          name: build_${{ matrix.os.runner }}${{ matrix.os.preset == 'linux-32' && '-32' || '' }}_${{ matrix.os.cxx }}
          path: |
            ${{ github.workspace }}/builds/${{ matrix.os.preset }}/Descent3/Debug/
            ${{ github.workspace }}/builds/${{ matrix.os.preset }}/Descent3/Release/
